### ISSUE TITLE
Installing in mac

### ISSUE THREAD

**Issue by MayuraVerma** [itfoundry/hind-mysuru#7]
While installing otf version of this font.

Mac Sierrra 10.12.3 shows there is a serious error in this font.

Mac doesn't allow to install this font.

Please check

![screen shot 2017-03-08 at 7 57 05 am](https://cloud.githubusercontent.com/assets/14062593/23706693/df31b2da-03d4-11e7-9fe4-bb62a1696de8.png)

![screen shot 2017-03-08 at 7 57 46 am](https://cloud.githubusercontent.com/assets/14062593/23706717/f22ed840-03d4-11e7-9381-e792df58fa1e.png)

**Comment by lianghai** [comment]
Can't reproduce this issue on macOS 10.12.3 when installing the OTFs from the repo's `/build` directory.
Can't find issues when validating either:
<img width="622" alt="screen shot 2017-03-15 at 15 21 28" src="https://cloud.githubusercontent.com/assets/343259/23937571/2c9530ce-0993-11e7-88a0-072b68b16807.png">

**Comment by MayuraVerma** [comment]
I re-downloaded the files and installed. It went through successful this time.

Thanks
